<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>$archiver</key>
	<string>NSKeyedArchiver</string>
	<key>$objects</key>
	<array>
		<string>$null</string>
		<string>4748</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>53</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>3</integer>
				</dict>
				<dict>
					<key>CF$UID</key>
					<integer>32</integer>
				</dict>
			</array>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>31</integer>
			</dict>
			<key>X</key>
			<dict>
				<key>CF$UID</key>
				<integer>4</integer>
			</dict>
			<key>Y</key>
			<dict>
				<key>CF$UID</key>
				<integer>5</integer>
			</dict>
			<key>barcolor</key>
			<dict>
				<key>CF$UID</key>
				<integer>22</integer>
			</dict>
			<key>barxleft</key>
			<false/>
			<key>barxright</key>
			<false/>
			<key>barybottom</key>
			<false/>
			<key>barytop</key>
			<false/>
			<key>belongx</key>
			<integer>1</integer>
			<key>belongy</key>
			<integer>1</integer>
			<key>byteorder</key>
			<integer>0</integer>
			<key>color</key>
			<dict>
				<key>CF$UID</key>
				<integer>10</integer>
			</dict>
			<key>comment</key>
			<dict>
				<key>CF$UID</key>
				<integer>8</integer>
			</dict>
			<key>dash</key>
			<integer>0</integer>
			<key>dashwidth</key>
			<real>0.0</real>
			<key>dynsize</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>errorbarx</key>
			<integer>0</integer>
			<key>errorbary</key>
			<integer>0</integer>
			<key>errorcolor</key>
			<dict>
				<key>CF$UID</key>
				<integer>28</integer>
			</dict>
			<key>errorvalx</key>
			<real>0.0</real>
			<key>errorvaly</key>
			<real>0.0</real>
			<key>errorwidth</key>
			<real>1</real>
			<key>fillcolor</key>
			<dict>
				<key>CF$UID</key>
				<integer>18</integer>
			</dict>
			<key>freex</key>
			<false/>
			<key>freey</key>
			<false/>
			<key>fxmax</key>
			<real>1</real>
			<key>fxmin</key>
			<real>0.0</real>
			<key>fymax</key>
			<real>1</real>
			<key>fymin</key>
			<real>0.0</real>
			<key>havexminmax</key>
			<true/>
			<key>haveyminmax</key>
			<true/>
			<key>linewidth</key>
			<real>2</real>
			<key>plotarea</key>
			<false/>
			<key>plotdots</key>
			<false/>
			<key>plotfhist</key>
			<false/>
			<key>plothist</key>
			<false/>
			<key>plotlegend</key>
			<true/>
			<key>plotlines</key>
			<true/>
			<key>plotsymbols</key>
			<false/>
			<key>plotxbars</key>
			<false/>
			<key>plotxsticks</key>
			<false/>
			<key>plotybars</key>
			<false/>
			<key>plotysticks</key>
			<false/>
			<key>show</key>
			<false/>
			<key>source</key>
			<dict>
				<key>CF$UID</key>
				<integer>6</integer>
			</dict>
			<key>stickabs</key>
			<false/>
			<key>stickcolor</key>
			<dict>
				<key>CF$UID</key>
				<integer>25</integer>
			</dict>
			<key>sticksize</key>
			<real>0.0</real>
			<key>symbol</key>
			<integer>0</integer>
			<key>symbolsize</key>
			<real>20</real>
			<key>symfill</key>
			<false/>
			<key>verno</key>
			<integer>31</integer>
		</dict>
		<data>
		XeFdLuI7/D+GPe3w12T8P6+ZfLPNjfw/2PULdsO2/D8AUps4ud/8PymuKvuu
		CP0/Ugq6vaQx/T97ZkmAmlr9P6TC2EKQg/0/zR5oBYas/T/2evfHe9X9Px/X
		hopx/v0/SDMWTWcn/j9xj6UPXVD+P5rrNNJSef4/w0fElEii/j/so1NXPsv+
		PxUA4xk09P4/Plxy3Ckd/z9nuAGfH0b/P5AUkWEVb/8/uXAgJAuY/z/izK/m
		AMH/PwspP6n26f8/mkLnNXYJAECu8C4X8R0AQMOedvhrMgBA10y+2eZGAEDs
		+gW7YVsAQACpTZzcbwBAFVeVfVeEAEApBd1e0pgAQD6zJEBNrQBAUmFsIcjB
		AEBnD7QCQ9YAQHu9++O96gBAkGtDxTj/AECkGYumsxMBQLnH0ocuKAFAzXUa
		aak8AUDiI2JKJFEBQPbRqSufZQFACoDxDBp6AUAfLjnulI4BQDPcgM8PowFA
		SIrIsIq3AUBcOBCSBcwBQHHmV3OA4AFAhZSfVPv0AUCaQuc1dgkCQK7wLhfx
		HQJAw552+GsyAkDXTL7Z5kYCQOz6BbthWwJAAKlNnNxvAkAVV5V9V4QCQCkF
		3V7SmAJAPrMkQE2tAkBSYWwhyMECQGcPtAJD1gJAe737473qAkCQa0PFOP8C
		QKQZi6azEwNAucfShy4oA0DNdRppqTwDQOIjYkokUQNA9tGpK59lA0AKgPEM
		GnoDQB8uOe6UjgNAM9yAzw+jA0BIisiwircDQFw4EJIFzANAceZXc4DgA0CF
		lJ9U+/QDQJpC5zV2CQRArvAuF/EdBEDDnnb4azIEQNdMvtnmRgRA7PoFu2Fb
		BEAAqU2c3G8EQBVXlX1XhARAKQXdXtKYBEA+syRATa0EQFJhbCHIwQRAZw+0
		AkPWBEB7vfvjveoEQJBrQ8U4/wRApBmLprMTBUC5x9KHLigFQM11GmmpPAVA
		4iNiSiRRBUD20akrn2UFQAqA8QwaegVAHy457pSOBUAz3IDPD6MFQEiKyLCK
		twVAXDgQkgXMBUBx5ldzgOAFQIWUn1T79AVAmkLnNXYJBkCu8C4X8R0GQMOe
		dvhrMgZA10y+2eZGBkDs+gW7YVsGQACpTZzcbwZAFVeVfVeEBkApBd1e0pgG
		QD6zJEBNrQZAUmFsIcjBBkBnD7QCQ9YGQHu9++O96gZAkGtDxTj/BkCkGYum
		sxMHQLnH0ocuKAdAzXUaaak8B0DiI2JKJFEHQPbRqSufZQdACoDxDBp6B0Af
		LjnulI4HQDPcgM8PowdASIrIsIq3B0BcOBCSBcwHQHHmV3OA4AdAhZSfVPv0
		B0CaQuc1dgkIQK7wLhfxHQhAw552+GsyCEDXTL7Z5kYIQOz6BbthWwhAAKlN
		nNxvCEAVV5V9V4QIQCkF3V7SmAhAPrMkQE2tCEBSYWwhyMEIQGcPtAJD1ghA
		e737473qCECQa0PFOP8IQKQZi6azEwlAucfShy4oCUDNdRppqTwJQOIjYkok
		UQlA9tGpK59lCUAKgPEMGnoJQB8uOe6UjglAM9yAzw+jCUBIisiwircJQFw4
		EJIFzAlAceZXc4DgCUCFlJ9U+/QJQJpC5zV2CQpArvAuF/EdCkDDnnb4azIK
		QNdMvtnmRgpA7PoFu2FbCkAAqU2c3G8KQBVXlX1XhApAKQXdXtKYCkA+syRA
		Ta0KQFJhbCHIwQpAZw+0AkPWCkB7vfvjveoKQJBrQ8U4/wpApBmLprMTC0C5
		x9KHLigLQM11GmmpPAtA4iNiSiRRC0D20akrn2ULQAqA8QwaegtAHy457pSO
		C0Az3IDPD6MLQEiKyLCKtwtAXDgQkgXMC0Bx5ldzgOALQIWUn1T79AtAmkLn
		NXYJDECu8C4X8R0MQMOedvhrMgxA10y+2eZGDEDs+gW7YVsMQACpTZzcbwxA
		FVeVfVeEDEApBd1e0pgMQD6zJEBNrQxAUmFsIcjBDEBnD7QCQ9YMQHu9++O9
		6gxAkGtDxTj/DECkGYumsxMNQLnH0ocuKA1AzXUaaak8DUDiI2JKJFENQPbR
		qSufZQ1ACoDxDBp6DUAfLjnulI4NQDPcgM8Pow1ASIrIsIq3DUBcOBCSBcwN
		QHHmV3OA4A1AhZSfVPv0DUCaQuc1dgkOQK7wLhfxHQ5AxZ52+GsyDkDXTL7Z
		5kYOQOz6BbthWw5AAKlNnNxvDkAVV5V9V4QOQCkF3V7SmA5APrMkQE2tDkBS
		YWwhyMEOQGcPtAJD1g5Ae737473qDkCQa0PFOP8OQKQZi6azEw9AucfShy4o
		D0DNdRppqTwPQOIjYkokUQ9A9tGpK59lD0AKgPEMGnoPQB8uOe6Ujg9AM9yA
		zw+jD0BIisiwircPQFw4EJIFzA9AceZXc4DgD0CFlJ9U+/QPQE2h8xq7BBBA
		V3iXi/gOEEBjTzv8NRkQQGwm32xzIxBAdv2C3bAtEECA1CZO7jcQQIuryr4r
		QhBAlYJuL2lMEECfWRKgplYQQKkwthDkYBBAswdagSFrEEC+3v3xXnUQQMi1
		oWKcfxBA0oxF09mJEEDcY+lDF5QQQOc6jbRUnhBA8RExJZKoEED76NSVz7IQ
		QAXAeAYNvRBAD5ccd0rHEEAabsDnh9EQQCRFZFjF2xBALhwIyQLmEEA486s5
		QPAQQEPKT6p9+hBATaHzGrsEEUBXeJeL+A4RQGFPO/w1GRFAbCbfbHMjEUB2
		/YLdsC0RQIDUJk7uNxFAiqvKvitCEUCVgm4vaUwRQJ9ZEqCmVhFAqTC2EORg
		EUCzB1qBIWsRQL7e/fFedRFAyLWhYpx/EUDSjEXT2YkRQNxj6UMXlBFA5zqN
		tFSeEUDxETElkqgRQPvo1JXPshFABcB4Bg29EUAPlxx3SscRQBpuwOeH0RFA
		JEVkWMXbEUAuHAjJAuYRQDjzqzlA8BFAQ8pPqn36EUBNofMauwQSQFd4l4v4
		DhJAYU87/DUZEkBsJt9scyMSQHb9gt2wLRJAgNQmTu43EkCKq8q+K0ISQJWC
		bi9pTBJAn1kSoKZWEkCpMLYQ5GASQLMHWoEhaxJAvt798V51EkDItaFinH8S
		QNKMRdPZiRJA3GPpQxeUEkDnOo20VJ4SQPERMSWSqBJA++jUlc+yEkAFwHgG
		Db0SQA+XHHdKxxJAGm7A54fREkAkRWRYxdsSQC4cCMkC5hJAOPOrOUDwEkBD
		yk+qffoSQE2h8xq7BBNAV3iXi/gOE0BhTzv8NRkTQGwm32xzIxNAdv2C3bAt
		E0CA1CZO7jcTQIqryr4rQhNAlYJuL2lME0CfWRKgplYTQKkwthDkYBNAswda
		gSFrE0C+3v3xXnUTQMi1oWKcfxNA0oxF09mJE0DcY+lDF5QTQOc6jbRUnhNA
		8RExJZKoE0D76NSVz7ITQAXAeAYNvRNAD5ccd0rHE0AabsDnh9ETQCRFZFjF
		2xNALhwIyQLmE0A486s5QPATQEPKT6p9+hNATaHzGrsEFEBXeJeL+A4UQGFP
		O/w1GRRAbCbfbHMjFEB2/YLdsC0UQIDUJk7uNxRAiqvKvitCFECVgm4vaUwU
		QJ9ZEqCmVhRAqTC2EORgFECzB1qBIWsUQL7e/fFedRRAyLWhYpx/FEDSjEXT
		2YkUQNxj6UMXlBRA5zqNtFSeFEDxETElkqgUQPvo1JXPshRABcB4Bg29FEAP
		lxx3SscUQBpuwOeH0RRAJEVkWMXbFEAuHAjJAuYUQDjzqzlA8BRAQ8pPqn36
		FEBNofMauwQVQFd4l4v4DhVAYU87/DUZFUBsJt9scyMVQHb9gt2wLRVAgNQm
		Tu43FUCKq8q+K0IVQJWCbi9pTBVAn1kSoKZWFUCpMLYQ5GAVQLMHWoEhaxVA
		vt798V51FUDItaFinH8VQNKMRdPZiRVA3GPpQxeUFUDnOo20VJ4VQPERMSWS
		qBVA++jUlc+yFUAFwHgGDb0VQA+XHHdKxxVAGm7A54fRFUAkRWRYxdsVQC4c
		CMkC5hVAOPOrOUDwFUBDyk+qffoVQE2h8xq7BBZAV3iXi/gOFkBhTzv8NRkW
		QGwm32xzIxZAdv2C3bAtFkCA1CZO7jcWQIqryr4rQhZAlYJuL2lMFkCfWRKg
		plYWQKkwthDkYBZAswdagSFrFkC+3v3xXnUWQMi1oWKcfxZA0oxF09mJFkDc
		Y+lDF5QWQOc6jbRUnhZA8RExJZKoFkD76NSVz7IWQAXAeAYNvRZAD5ccd0rH
		FkAabsDnh9EWQCRFZFjF2xZALhwIyQLmFkA486s5QPAWQEPKT6p9+hZATaHz
		GrsEF0BXeJeL+A4XQGFPO/w1GRdAaybfbHMjF0B2/YLdsC0XQIDUJk7uNxdA
		iqvKvitCF0CTgm4vaUwXQJ9ZEqCmVhdAqTC2EORgF0CzB1qBIWsXQL7e/fFe
		dRdAyLWhYpx/F0DSjEXT2YkXQNxj6UMXlBdA5zqNtFSeF0DxETElkqgXQPvo
		1JXPshdABcB4Bg29F0APlxx3SscXQBluwOeH0RdAJEVkWMXbF0AuHAjJAuYX
		QDjzqzlA8BdAQ8pPqn36F0BNofMauwQYQFd4l4v4DhhAYU87/DUZGEBrJt9s
		cyMYQHb9gt2wLRhAgNQmTu43GECKq8q+K0IYQJOCbi9pTBhAn1kSoKZWGECp
		MLYQ5GAYQLMHWoEhaxhAvt798V51GEDItaFinH8YQNKMRdPZiRhA3GPpQxeU
		GEDnOo20VJ4YQPERMSWSqBhA++jUlc+yGEAFwHgGDb0YQA+XHHdKxxhAGW7A
		54fRGEAkRWRYxdsYQC4cCMkC5hhAOPOrOUDwGEBDyk+qffoYQE2h8xq7BBlA
		V3iXi/gOGUBhTzv8NRkZQGsm32xzIxlAdv2C3bAtGUCA1CZO7jcZQIqryr4r
		QhlAk4JuL2lMGUCfWRKgplYZQKkwthDkYBlAswdagSFrGUC+3v3xXnUZQMi1
		oWKcfxlA0oxF09mJGUDcY+lDF5QZQOc6jbRUnhlA8RExJZKoGUD76NSVz7IZ
		QAXAeAYNvRlAD5ccd0rHGUAabsDnh9EZQCRFZFjF2xlALhwIyQLmGUA486s5
		QPAZQEPKT6p9+hlATaHzGrsEGkBXeJeL+A4aQGFPO/w1GRpAaybfbHMjGkB2
		/YLdsC0aQIDUJk7uNxpAiqvKvitCGkCTgm4vaUwaQJ9ZEqCmVhpAqTC2EORg
		GkCzB1qBIWsaQL7e/fFedRpAyLWhYpx/GkDSjEXT2YkaQNxj6UMXlBpA5zqN
		tFSeGkDxETElkqgaQPvo1JXPshpABcB4Bg29GkAPlxx3SscaQBpuwOeH0RpA
		JEVkWMXbGkAuHAjJAuYaQDjzqzlA8BpAQ8pPqn36GkBNofMauwQbQFd4l4v4
		DhtA
		</data>
		<data>
		Hh6OCs/w+r9/QOoEFS77v3tD0lV6a/u/j9bWj/6o+7/hPOOuaR/8v0Wt+l7C
		Xfy/50PXwDmc/L9Ugxt5z9r8v6vUBS2DGf2/xM5sglRY/b+jn7sfQ5f9v9wE
		z49O1v2/iRjrr3YV/r/OZVMOu1T+v6wKnVMblP6/1pLgKJfT/r9t67Y3LhP/
		v45vNirgUv+/sCjwqqyS/7/hKe1kk9L/v8j01QFKCQDAeeeOGVcpAMD/cdLP
		cEkAwDC4CPuWaQDAOvTPccmJAMBwUvsKCKoAwMsWkp1SygDAUIDOAKnqAMD8
		8BwMCwsBwPMAG5d4KwHAlKeWefFLAcD+c42LdWwBwP6kK6UEjQHAxorLnp6t
		AcBnsfRQQ84BwMouW5Ty7gHAXwbfQawPAsCebosycDACwF4klj8+UQLAFvle
		QhZyAsDtzW4U+JICwGCRd4/jswLAgw9TjdjUAsB3+ALo1vUCwGh0r3neFgPA
		F/inHO83A8D2bzzQCFkDwCfZ/CcregPAQncDIVabA8A0gjaWibwDwKn/nmLF
		3QPAt9VpYQn/A8BU9OZtVSAEwJWIh2OpQQTAAYvdHQVjBMBJDJ54aIQEwMtN
		nU/TpQTAlMvMfkXHBMApS0DivugEwKznJ1Y/CgXA1E7RtsYrBcBmKajgVE0F
		wNi3MLDpbgXAOPoMAoWQBcBaPfiyJrIFwBX8yJ/O0wXAboVmpXz1BcBd9tmg
		MBcGwIQtSBb9WAbAwajbJTp7BsAWw0OzfJ0GwOD2UZXEvwbAw3mZxRHiBsCS
		DQQfZAQHwBMGwoW7JgfARLEq3hdJB8BtZLkMeWsHwI5+C/bejQfAqCXdfkmw
		B8BQqwaMuNIHwG23J9qzCgjAGMqd/2stCMB6p4C5KFAIwF6uMfHpcgjAONA6
		kK+VCMDuHU+AebgIwGZASKtH2wjAem0k+xn+CMD3mAVa8CAJwK1QL7LKQwnA
		My533KhmCcDPLZ/kiokJwLXHbaVwrAnAiZydCVrPCcAQwgT8RvIJwIUXlGc3
		FQrA2NNVNys4CsCx/WxWIlsKwPAgFLAcfgrAi2icLxqhCsDt/mzAGsQKwKy6
		AU4e5wrAtNbqwyQKC8C8dMsNLi0LwBbVWRc6UAvAcMNdzEhzC8A4YbAYWpYL
		wHiKO+htuQvAht8EKITcC8DA8cjBnP8LwC1w4qK3IgzAmTZ6t9RFDMBF28br
		82gMwHQCDCwVjAzAaoCaZDivDMDfxc+BXdIMwDHkFXCE9QzAVEjjG60YDcBM
		sZJI7i4NwOOyk2FLUg3AlkTZbal1DcDt+xRZCJkNwDI3Ew9ovA3ACEO6e8jf
		DcAQvwmLKQMOwONwGSmLJg7AbfcYQu1JDsByZE/CT20OwFARGpaykA7A297r
		qRW0DsCiNk3qeNcOwLFF2kPc+g7ANABDoz8eD8BVMEr1okEPwMOpxCYGZQ/A
		t9CYJGmID8BypL3by6sPwMaXOjkuzw/AtVwmKpDyD8DNY9PN+AoQwBrhdz2p
		HBDAn5OhWlkuEMAG1/cbCUAQwI1fKHi4URDAIbfmZWdjEMDKJezbFXUQwAkl
		99DDhhDAmUnLO3GYEMDa8TATHqoQwNrHUkPKuxDArHSP13XNEMCA+8a8IN8Q
		wNCv0OnK8BDAXGCHVXQCEcBHt8f2HBQRwKk9ccTEJRHApn9ktWs3EcA29oPA
		EUkRwI1665r2dxHAYE5oUA6KEcBe1iPNJJwRwIjKKA86rhHAg1ubFE7AEcBH
		ULjbYNIRwKnA1GJy5BHAmU9dpoL2EcAbnZaokQgSwIwzVmafGhLAGjNB36ss
		EsBacjsQtz4SwBw7EPnAUBLApXuzmMliEsCxNy/u0HQSwCd+o/jWhhLA9VRG
		t9uYEsBgo2Mp36oSwBR+XU7hvBLA492rJeLOEsBeNN2u4eASwMAolunf8hLA
		Nj2S1dwEE8DHGaRy2BYTwL3qtcDSKBPAqQfKv8s6E8BjXPtvw0wTwLZrftG5
		XhPAY7uh5K5wE8Cl2M6pooITwBNjiyGVlBPAX915TIamE8DnDlsrdrgTwPr+
		Dr9kyhPAbHiWCFLcE8DUghQJPu4TwJz2z8EoABTAxB01NBISFMBFztdh+iMU
		wBifDAxZQhTAwt/li1VUFMA3f9ogUGYUwBHDyctIeBTAcA2LjT+KFMBQdO1m
		NJwUwBFft1gnrhTAdBmmYxjAFMASi22IB9IUwErymcP04xTAMHEGH+D1FMAV
		FB6WyQcVwLDSGSmxGRXAXpAp2pYrFcC2B8emej0VwBHUIJFcTxXA6dCdmTxh
		FcCppJvAGnMVwATZbgb3hBXAaQBja9GWFcDsJ7vvqagVwHLysZOAuhXAEnN6
		V1XMFcAeAkA7KN4VwPzaJz/57xXAA9RQY8gBFsAGg9SnlRMWwBFYyAxhJRbA
		4xU+kio3FsASaEU48kgWwM3ufXgaTRbAg3LXE2RfFsC5cI0dqXEWwI0+R5Hp
		gxbABq+saiWWFsBknGKlXKgWwB5YDD2PuhbA62VGLb3MFsAcTaVx5t4WwG0+
		swUL8RbAcPXu5CoDF8Aua8cKRhUXwBrqmnJcJxfAwcC0F245F8DEfEz1eksX
		wPCnewaDXRfAbQlHRoZvF8DymZSvhIEXwA03KT1+kxfAUKh66XKlF8C9Uyd4
		/ckXwH2renRG3BfAd23BXIruF8AC5WMwyQAYwGcuyu4CExjAuoValzclGMD9
		gXcpZzcYwAOkfqSRSRjAvKrFB7dbGMBYBJtS120YwJcVQoTyfxjArmjymwiS
		GMBs1daYGaQYwC0iCXolthjAfrGVPizIGMB5k3PlLdoYwJQAhW0q7BjAcANi
		1SH+GMB48DEcFBAZwNkLW0ABIhnAFOdgQOkzGcD1z6oazEUZwDLUgc2pVxnA
		MXwPV4JpGcBUYlu1VXsZwM8USuYjjRnAGIGa5+yeGcAj0eS2sLAZwDGul1Fv
		whnA7/n2tCjUGcCJVhne3OUZwMHj5cmL9xnAwK8SdTUJGsA6piHc2RoawKJ1
		cvh4LBrABEPEyxI+GsB3BixPp08awOMLQ342YRrAuOtiVMByGsD4B6DMRIQa
		wNXcyOHDlRrA82Nhjj2nGsBeLqDMsbgawA4paZYgyhrAWOBM5YnbGsBRy4Cy
		7ewawB6a3fZL/hrANfPZqqQPG8ABk4PG9yAbwMGcfEFFMhvA9z72Eo1DG8AC
		GKsxz1QbwCKEp5cLZhvAwkEHKEJ3G8BMnWH4cogbwGBdrOSdmRvAJsS358Kq
		G8C7N8r04bsbwC14wVfP9xvAk1jWcLgJHMD1vLW4mhscwA5ykDR2LRzA45mK
		6Uo/HMATXbvcGFEcwOF6LBPgYhzAWiTakaB0HMBmebJdWoYcwBFdlXsNmBzA
		JEnc8LmpHMCVEUXBX7scwAwoAfL+zBzAbQG1h5feHMCRnPWGKfAcwER0SPS0
		AR3AYA0j1DkTHcBwKusquCQdwFIw9vwvNh3Ax3uJTqFHHcDH6NkjDFkdwJ7H
		C4Fwah3AQ+Iyas57HcD0XFLjJY0dwE2LXPB2nh3AlN4ylcGvHcD++aXVBcEd
		wHN7dbVD0h3AMu1POHvjHcDEBNNhrPQdwBJJizXXBR7AjyH0tvsWHsBbynfp
		GSgewCmVb9AxOR7AX3kjb0NKHsCWTsrITlsewE7nh7fNZB7AtSWKjkp2HsCF
		cYRov4cewCzffkwsmR7A7Q9wQZGqHsDJVDxO7rsewE/QtHlDzR7AvJaWypDe
		HsBu4YlH1u8ewADpIPcTAR/AgF7X30kSH8B4GhEIeCMfwGWZGXaeNB/AwElL
		ML1FH8BWvW481FYfwK4ApqDjZx/AjhzQYut4H8C7v66I64kfwHzD5Bfkmh/A
		/Qr1FdWrH8BPJUGIvrwfwIWXCHSgzR/A5ctm3nreH8CJHFLMTe8fwL0VTaEM
		ACDA4zfzom4IIMDQ81ntzBAgwIwUqoInGSDA02r1ZH4hIMAwuzWW0SkgwE60
		SxghMiDA2J797Gw6IMBFN/YVtUIgwALlwpT5SiDAZ1PSajpTIMBZoXKZd1sg
		wIeGzyGxYyDAvELwBOdrIMBSqoIWcn4gwPAldRUegyDA7bOaQd+LIMByDio4
		m5QgwENOzv9RnSDAEW8TnwOmIMDvZ3ocsK4gwPyBIn5XtyDAPKNJyvm/IMDq
		a/QGl8ggwEOeAjov0SDAE/YtacLZIMCEkQiaUOIgwO1E+9HZ6iDAWPZDFl7z
		IMBPk/Nr3fsgwA/v69dXBCHAHIndXs0MIcBp9UQFPhUhwBT0Z8+pHSHAbHFS
		wRAmIcBQOdPeci4hwMXhdyvQNiHAOumIqig/IcC5+ARffEchwIenm0vLTyHA
		l8anchVYIcCahwUvLW0hwPQ2SVPKdSHAi1J9N2J+IcBe8Fnj9IYhwJZohF6C
		jyHAGAqQsAqYIcDzqv/gjaAhwMMJQ/cLqSHAaja9+oSxIcBtkMHy+LkhwAIa
		luZnwiHAAId03dHKIcA6q4veNtMhwHAUAfGW2yHAIJ3yG/LjIcCQiXhmSOwh
		wM2mp9eZ9CHAxtGTdub8IcCGzFJKLgUiwJqW/1lxDSLAciC+rK8VIsCanr9J
		6R0iwACeRzgeJiLASrCxf04uIsA4YXgnejYiwOX7PDehPiLAvvvQtsNGIsBJ
		/ECu4U4iwMTn4SX7ViLA9W5gJhBfIsDn9dO4IGciwFkL1eYsbyLA9wCZujR3
		IsAefxM/OH8iwCHpH4A3hyLAIuq0ijKPIsB6oSRtKZciwA0fbjccnyLAbruk
		+wqnIsBd2XXO9a4iwO6g1sfctiLAjiLj9si7IsBcnoqJzsMiwJwucq7NyyLA
		tmg/acbTIsAmH1m9uNsiwCaP5K2k4yLAfHnCPYrrIsC7L0Aw9/ciwIOLXwpC
		ACPAL2YJDoYII8D7xl9EwxAjwK6RcLb5GCPAjPY1bSkhI8AQ3ZZxUikjwMlI
		Z8x0MSPANbpohpA5I8BbikqopUEjwLRCqjq0SSPAH/ATRrxRI8BrcwLTvVkj
		wN/M3+m4YSPAlWUFk61pI8DkVLzWm3EjwAmjPb2DeSPATomyTmWBI8AirzST
		QIkjwNhkzpIVkSPAWsVZJgGZI8BKkC7d6aAjwPdoHQvMqCPAaa0HuaewI8Ad
		/LPvfLgjwBhXz7dLwCPAnu3tGRTII8CXkYoe1s8jwEybDs6R1yPAD2/HMEff
		I8DkBu9O9uYjwC2cqjCf7iPAYUoL3kH2I8DNpg5f3v0jwLBQn7t0BSTAbHWV
		+wQNJMBZULcmjxQkwG6fuUQTHCTAsxRAXZEjJMC4vt13CSskwJBsFZx7MiTA
		Twta0ec5JMDrAA8fTkEkwDp/iIyuSCTABtULIQlQJMAVus/jXVckwF2Y/Nus
		XiTA
		</data>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string>Pasteboard</string>
		</dict>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSMutableString</string>
				<string>NSString</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSMutableString</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string>N=6, η=0</string>
		</dict>
		<string></string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>11</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>14</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>NSColor pasteboard type</string>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSMutableSet</string>
				<string>NSSet</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSMutableSet</string>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSColorSpace</key>
			<integer>3</integer>
			<key>NSWhite</key>
			<data>
			MAA=
			</data>
		</dict>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSColor</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSColor</string>
		</dict>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSColorWell</string>
				<string>NSControl</string>
				<string>NSView</string>
				<string>NSResponder</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSColorWell</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>21</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>19</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>20</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSColorSpace</key>
			<integer>3</integer>
			<key>NSWhite</key>
			<data>
			MC42NjY2NjY2NjY3AA==
			</data>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>23</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>24</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>26</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>27</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>29</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>30</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$classes</key>
			<array>
				<string>DataBuffer</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>DataBuffer</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>31</integer>
			</dict>
			<key>X</key>
			<dict>
				<key>CF$UID</key>
				<integer>33</integer>
			</dict>
			<key>Y</key>
			<dict>
				<key>CF$UID</key>
				<integer>34</integer>
			</dict>
			<key>barcolor</key>
			<dict>
				<key>CF$UID</key>
				<integer>44</integer>
			</dict>
			<key>barxleft</key>
			<false/>
			<key>barxright</key>
			<false/>
			<key>barybottom</key>
			<false/>
			<key>barytop</key>
			<false/>
			<key>belongx</key>
			<integer>1</integer>
			<key>belongy</key>
			<integer>1</integer>
			<key>byteorder</key>
			<integer>0</integer>
			<key>color</key>
			<dict>
				<key>CF$UID</key>
				<integer>37</integer>
			</dict>
			<key>comment</key>
			<dict>
				<key>CF$UID</key>
				<integer>36</integer>
			</dict>
			<key>dash</key>
			<integer>0</integer>
			<key>dashwidth</key>
			<real>0.0</real>
			<key>dynsize</key>
			<dict>
				<key>CF$UID</key>
				<integer>9</integer>
			</dict>
			<key>errorbarx</key>
			<integer>0</integer>
			<key>errorbary</key>
			<integer>0</integer>
			<key>errorcolor</key>
			<dict>
				<key>CF$UID</key>
				<integer>50</integer>
			</dict>
			<key>errorvalx</key>
			<real>0.0</real>
			<key>errorvaly</key>
			<real>0.0</real>
			<key>errorwidth</key>
			<real>1</real>
			<key>fillcolor</key>
			<dict>
				<key>CF$UID</key>
				<integer>41</integer>
			</dict>
			<key>freex</key>
			<false/>
			<key>freey</key>
			<false/>
			<key>fxmax</key>
			<real>1</real>
			<key>fxmin</key>
			<real>0.0</real>
			<key>fymax</key>
			<real>1</real>
			<key>fymin</key>
			<real>0.0</real>
			<key>havexminmax</key>
			<true/>
			<key>haveyminmax</key>
			<true/>
			<key>linewidth</key>
			<real>2</real>
			<key>plotarea</key>
			<false/>
			<key>plotdots</key>
			<false/>
			<key>plotfhist</key>
			<false/>
			<key>plothist</key>
			<false/>
			<key>plotlegend</key>
			<true/>
			<key>plotlines</key>
			<true/>
			<key>plotsymbols</key>
			<false/>
			<key>plotxbars</key>
			<false/>
			<key>plotxsticks</key>
			<false/>
			<key>plotybars</key>
			<false/>
			<key>plotysticks</key>
			<false/>
			<key>show</key>
			<true/>
			<key>source</key>
			<dict>
				<key>CF$UID</key>
				<integer>35</integer>
			</dict>
			<key>stickabs</key>
			<false/>
			<key>stickcolor</key>
			<dict>
				<key>CF$UID</key>
				<integer>47</integer>
			</dict>
			<key>sticksize</key>
			<real>0.0</real>
			<key>symbol</key>
			<integer>0</integer>
			<key>symbolsize</key>
			<real>20</real>
			<key>symfill</key>
			<false/>
			<key>verno</key>
			<integer>31</integer>
		</dict>
		<data>
		XeFdLuI7/D+GPe3w12T8P6+ZfLPNjfw/2PULdsO2/D8AUps4ud/8PymuKvuu
		CP0/Ugq6vaQx/T97ZkmAmlr9P6TC2EKQg/0/zR5oBYas/T/2evfHe9X9Px/X
		hopx/v0/SDMWTWcn/j9xj6UPXVD+P5rrNNJSef4/w0fElEii/j/so1NXPsv+
		PxUA4xk09P4/Plxy3Ckd/z9nuAGfH0b/P5AUkWEVb/8/uXAgJAuY/z/izK/m
		AMH/PwspP6n26f8/mkLnNXYJAECu8C4X8R0AQMOedvhrMgBA10y+2eZGAEDs
		+gW7YVsAQACpTZzcbwBAFVeVfVeEAEApBd1e0pgAQD6zJEBNrQBAUmFsIcjB
		AEBnD7QCQ9YAQHu9++O96gBAkGtDxTj/AECkGYumsxMBQLnH0ocuKAFAzXUa
		aak8AUDiI2JKJFEBQPbRqSufZQFACoDxDBp6AUAfLjnulI4BQDPcgM8PowFA
		SIrIsIq3AUBcOBCSBcwBQHHmV3OA4AFAhZSfVPv0AUCaQuc1dgkCQK7wLhfx
		HQJAw552+GsyAkDXTL7Z5kYCQOz6BbthWwJAAKlNnNxvAkAVV5V9V4QCQCkF
		3V7SmAJAPrMkQE2tAkBSYWwhyMECQGcPtAJD1gJAe737473qAkCQa0PFOP8C
		QKQZi6azEwNAucfShy4oA0DNdRppqTwDQOIjYkokUQNA9tGpK59lA0AKgPEM
		GnoDQB8uOe6UjgNAM9yAzw+jA0BIisiwircDQFw4EJIFzANAceZXc4DgA0CF
		lJ9U+/QDQJpC5zV2CQRArvAuF/EdBEDDnnb4azIEQNdMvtnmRgRA7PoFu2Fb
		BEAAqU2c3G8EQBVXlX1XhARAKQXdXtKYBEA+syRATa0EQFJhbCHIwQRAZw+0
		AkPWBEB7vfvjveoEQJBrQ8U4/wRApBmLprMTBUC5x9KHLigFQM11GmmpPAVA
		4iNiSiRRBUD20akrn2UFQAqA8QwaegVAHy457pSOBUAz3IDPD6MFQEiKyLCK
		twVAXDgQkgXMBUBx5ldzgOAFQIWUn1T79AVAmkLnNXYJBkCu8C4X8R0GQMOe
		dvhrMgZA10y+2eZGBkDs+gW7YVsGQACpTZzcbwZAFVeVfVeEBkApBd1e0pgG
		QD6zJEBNrQZAUmFsIcjBBkBnD7QCQ9YGQHu9++O96gZAkGtDxTj/BkCkGYum
		sxMHQLnH0ocuKAdAzXUaaak8B0DiI2JKJFEHQPbRqSufZQdACoDxDBp6B0Af
		LjnulI4HQDPcgM8PowdASIrIsIq3B0BcOBCSBcwHQHHmV3OA4AdAhZSfVPv0
		B0CaQuc1dgkIQK7wLhfxHQhAw552+GsyCEDXTL7Z5kYIQOz6BbthWwhAAKlN
		nNxvCEAVV5V9V4QIQCkF3V7SmAhAPrMkQE2tCEBSYWwhyMEIQGcPtAJD1ghA
		e737473qCECQa0PFOP8IQKQZi6azEwlAucfShy4oCUDNdRppqTwJQOIjYkok
		UQlA9tGpK59lCUAKgPEMGnoJQB8uOe6UjglAM9yAzw+jCUBIisiwircJQFw4
		EJIFzAlAceZXc4DgCUCFlJ9U+/QJQJpC5zV2CQpArvAuF/EdCkDDnnb4azIK
		QNdMvtnmRgpA7PoFu2FbCkAAqU2c3G8KQBVXlX1XhApAKQXdXtKYCkA+syRA
		Ta0KQFJhbCHIwQpAZw+0AkPWCkB7vfvjveoKQJBrQ8U4/wpApBmLprMTC0C5
		x9KHLigLQM11GmmpPAtA4iNiSiRRC0D20akrn2ULQAqA8QwaegtAHy457pSO
		C0Az3IDPD6MLQEiKyLCKtwtAXDgQkgXMC0Bx5ldzgOALQIWUn1T79AtAmkLn
		NXYJDECu8C4X8R0MQMOedvhrMgxA10y+2eZGDEDs+gW7YVsMQACpTZzcbwxA
		FVeVfVeEDEApBd1e0pgMQD6zJEBNrQxAUmFsIcjBDEBnD7QCQ9YMQHu9++O9
		6gxAkGtDxTj/DECkGYumsxMNQLnH0ocuKA1AzXUaaak8DUDiI2JKJFENQPbR
		qSufZQ1ACoDxDBp6DUAfLjnulI4NQDPcgM8Pow1ASIrIsIq3DUBcOBCSBcwN
		QHHmV3OA4A1AhZSfVPv0DUCaQuc1dgkOQK7wLhfxHQ5AxZ52+GsyDkDXTL7Z
		5kYOQOz6BbthWw5AAKlNnNxvDkAVV5V9V4QOQCkF3V7SmA5APrMkQE2tDkBS
		YWwhyMEOQGcPtAJD1g5Ae737473qDkCQa0PFOP8OQKQZi6azEw9AucfShy4o
		D0DNdRppqTwPQOIjYkokUQ9A9tGpK59lD0AKgPEMGnoPQB8uOe6Ujg9AM9yA
		zw+jD0BIisiwircPQFw4EJIFzA9AceZXc4DgD0CFlJ9U+/QPQE2h8xq7BBBA
		V3iXi/gOEEBjTzv8NRkQQGwm32xzIxBAdv2C3bAtEECA1CZO7jcQQIuryr4r
		QhBAlYJuL2lMEECfWRKgplYQQKkwthDkYBBAswdagSFrEEC+3v3xXnUQQMi1
		oWKcfxBA0oxF09mJEEDcY+lDF5QQQOc6jbRUnhBA8RExJZKoEED76NSVz7IQ
		QAXAeAYNvRBAD5ccd0rHEEAabsDnh9EQQCRFZFjF2xBALhwIyQLmEEA486s5
		QPAQQEPKT6p9+hBATaHzGrsEEUBXeJeL+A4RQGFPO/w1GRFAbCbfbHMjEUB2
		/YLdsC0RQIDUJk7uNxFAiqvKvitCEUCVgm4vaUwRQJ9ZEqCmVhFAqTC2EORg
		EUCzB1qBIWsRQL7e/fFedRFAyLWhYpx/EUDSjEXT2YkRQNxj6UMXlBFA5zqN
		tFSeEUDxETElkqgRQPvo1JXPshFABcB4Bg29EUAPlxx3SscRQBpuwOeH0RFA
		JEVkWMXbEUAuHAjJAuYRQDjzqzlA8BFAQ8pPqn36EUBNofMauwQSQFd4l4v4
		DhJAYU87/DUZEkBsJt9scyMSQHb9gt2wLRJAgNQmTu43EkCKq8q+K0ISQJWC
		bi9pTBJAn1kSoKZWEkCpMLYQ5GASQLMHWoEhaxJAvt798V51EkDItaFinH8S
		QNKMRdPZiRJA3GPpQxeUEkDnOo20VJ4SQPERMSWSqBJA++jUlc+yEkAFwHgG
		Db0SQA+XHHdKxxJAGm7A54fREkAkRWRYxdsSQC4cCMkC5hJAOPOrOUDwEkBD
		yk+qffoSQE2h8xq7BBNAV3iXi/gOE0BhTzv8NRkTQGwm32xzIxNAdv2C3bAt
		E0CA1CZO7jcTQIqryr4rQhNAlYJuL2lME0CfWRKgplYTQKkwthDkYBNAswda
		gSFrE0C+3v3xXnUTQMi1oWKcfxNA0oxF09mJE0DcY+lDF5QTQOc6jbRUnhNA
		8RExJZKoE0D76NSVz7ITQAXAeAYNvRNAD5ccd0rHE0AabsDnh9ETQCRFZFjF
		2xNALhwIyQLmE0A486s5QPATQEPKT6p9+hNATaHzGrsEFEBXeJeL+A4UQGFP
		O/w1GRRAbCbfbHMjFEB2/YLdsC0UQIDUJk7uNxRAiqvKvitCFECVgm4vaUwU
		QJ9ZEqCmVhRAqTC2EORgFECzB1qBIWsUQL7e/fFedRRAyLWhYpx/FEDSjEXT
		2YkUQNxj6UMXlBRA5zqNtFSeFEDxETElkqgUQPvo1JXPshRABcB4Bg29FEAP
		lxx3SscUQBpuwOeH0RRAJEVkWMXbFEAuHAjJAuYUQDjzqzlA8BRAQ8pPqn36
		FEBNofMauwQVQFd4l4v4DhVAYU87/DUZFUBsJt9scyMVQHb9gt2wLRVAgNQm
		Tu43FUCKq8q+K0IVQJWCbi9pTBVAn1kSoKZWFUCpMLYQ5GAVQLMHWoEhaxVA
		vt798V51FUDItaFinH8VQNKMRdPZiRVA3GPpQxeUFUDnOo20VJ4VQPERMSWS
		qBVA++jUlc+yFUAFwHgGDb0VQA+XHHdKxxVAGm7A54fRFUAkRWRYxdsVQC4c
		CMkC5hVAOPOrOUDwFUBDyk+qffoVQE2h8xq7BBZAV3iXi/gOFkBhTzv8NRkW
		QGwm32xzIxZAdv2C3bAtFkCA1CZO7jcWQIqryr4rQhZAlYJuL2lMFkCfWRKg
		plYWQKkwthDkYBZAswdagSFrFkC+3v3xXnUWQMi1oWKcfxZA0oxF09mJFkDc
		Y+lDF5QWQOc6jbRUnhZA8RExJZKoFkD76NSVz7IWQAXAeAYNvRZAD5ccd0rH
		FkAabsDnh9EWQCRFZFjF2xZALhwIyQLmFkA486s5QPAWQEPKT6p9+hZATaHz
		GrsEF0BXeJeL+A4XQGFPO/w1GRdAaybfbHMjF0B2/YLdsC0XQIDUJk7uNxdA
		iqvKvitCF0CTgm4vaUwXQJ9ZEqCmVhdAqTC2EORgF0CzB1qBIWsXQL7e/fFe
		dRdAyLWhYpx/F0DSjEXT2YkXQNxj6UMXlBdA5zqNtFSeF0DxETElkqgXQPvo
		1JXPshdABcB4Bg29F0APlxx3SscXQBluwOeH0RdAJEVkWMXbF0AuHAjJAuYX
		QDjzqzlA8BdAQ8pPqn36F0BNofMauwQYQFd4l4v4DhhAYU87/DUZGEBrJt9s
		cyMYQHb9gt2wLRhAgNQmTu43GECKq8q+K0IYQJOCbi9pTBhAn1kSoKZWGECp
		MLYQ5GAYQLMHWoEhaxhAvt798V51GEDItaFinH8YQNKMRdPZiRhA3GPpQxeU
		GEDnOo20VJ4YQPERMSWSqBhA++jUlc+yGEAFwHgGDb0YQA+XHHdKxxhAGW7A
		54fRGEAkRWRYxdsYQC4cCMkC5hhAOPOrOUDwGEBDyk+qffoYQE2h8xq7BBlA
		V3iXi/gOGUBhTzv8NRkZQGsm32xzIxlAdv2C3bAtGUCA1CZO7jcZQIqryr4r
		QhlAk4JuL2lMGUCfWRKgplYZQKkwthDkYBlAswdagSFrGUC+3v3xXnUZQMi1
		oWKcfxlA0oxF09mJGUDcY+lDF5QZQOc6jbRUnhlA8RExJZKoGUD76NSVz7IZ
		QAXAeAYNvRlAD5ccd0rHGUAabsDnh9EZQCRFZFjF2xlALhwIyQLmGUA486s5
		QPAZQEPKT6p9+hlATaHzGrsEGkBXeJeL+A4aQGFPO/w1GRpAaybfbHMjGkB2
		/YLdsC0aQIDUJk7uNxpAiqvKvitCGkCTgm4vaUwaQJ9ZEqCmVhpAqTC2EORg
		GkCzB1qBIWsaQL7e/fFedRpAyLWhYpx/GkDSjEXT2YkaQNxj6UMXlBpA5zqN
		tFSeGkDxETElkqgaQPvo1JXPshpABcB4Bg29GkAPlxx3SscaQBpuwOeH0RpA
		JEVkWMXbGkAuHAjJAuYaQDjzqzlA8BpAQ8pPqn36GkBNofMauwQbQFd4l4v4
		DhtA
		</data>
		<data>
		SPgNxsIG+7/E0f0TYEX7v2UakY0nhPu/zX24eBjD+7/S4LnB1QH8v6Hmv/av
		QPy/SscTV7x//L/AVp5Z+r78v6fI2ldp/vy/Yp+xjAg+/b9myWAT1339v5Vn
		bubTvf2/Iuag3v39/b+6L/2xUz7+v6j+wvLTfv6/axpmDn2//r+m6XtMTQD/
		v8Z/ms1CQf+/4CEgiluC/79K7d1QlcP/v9+HzeJ2AgDApR61LzEjAMCQZ2Iz
		+EMAwNxNsXnKZADAunbfdKaFAMBZNyB8iqYAwHMX+Ml0xwDA7/5XemPoAMDl
		z2yIVAkBwLPM3LlFKgHA0O3S5DRLAcAWG/B+H2wBwBF/vuICjQHAftLZQ92t
		AcCoXv2erc4BwDHX5cBw7wHAbDARkS0QAsA8LW7I9zACwByaciDQUQLAMwpI
		rrZyAsDONiiIq5MCwPw0VcWutALAUtgNfsDVAsDcyH3L4PYCwBeXqscPGAPA
		rKpZjU05A8BFULiWm1oDwF3Bb377ewPAZXRMk22dA8B8LSQk8r4DwLUlUX+J
		4APAFUof8jMCBMDmECbI8SMEwC/DkErDRQTAg3JSv6hnBMBZ5kloookEwIf7
		TYKwqwTA5ikqRNPNBMCF5YXdCvAEwMhduHVXEgXAAPOOKrk0BcAszOYOMFcF
		wIMx9NS7eQXApyF1J1ycBcB/zvnrEL8FwAkbBvrZ4QXAB3MmGrcEBsBwTxUF
		qCcGwJ3z+mSASgbAkpP6iWxtBsDu8vLacJAGwHXju+uMswbAiynfNMDWBsAe
		+b0SCvoGwEVv0MRpHQfANOL/bN5AB8AhDRoPZ2QHwFf0XJACiAfA714Yt6+r
		B8CY5WEqbc8HwL06JEEe8wfAkvHUpdQWCMA18Cz5mToIwOwyW4dsXgjAfUOu
		d0qCCMCvm/jLMaYIwBH03l8gygjA8JcG6BPuCMADJhrxCRIJwNVkmN7/NQnA
		8DVi6fJZCcDpKfgd4H0JwN6qWlrEoQnAGP56S5zFCcDmFytqZOkJwOvwd/cY
		DQrAYGZX+LUwCsDVNo4wN1QKwKugHlOYdwrAymHgdeuaCsBtlXTVPb4KwLBs
		klmO4QrAIIsG1NsEC8Bifp7+JCgLwEmy5HhoSwvA4OeqxaRuC8CqG2JI2JEL
		wFmJQEIBtQvAdy82zx3YC8C6vArkK/sLwIXe22IqHgzA7Oe/lSZBDMCgIzf9
		JGQMwLbcd5IlhwzA9M59UCiqDMDja9sxLc0MwDArGTQ08AzAEP3/Uj0TDcAo
		718zRjYNwO4l8yNPWQ3AibRdNlp8DcD0Nz9rZ58NwMsdA8N2wg3AdOzLPYjl
		DcBp1F/bmwgOwAAgFJuxKw7Aai66e8lODsCsztZ843EOwJHT/MH/lA7ATBK5
		KiS4DsAnJzg2VNsOwMrUFJyQ/g7Ar1NpEtohD8Bdr2ZNMUUPwKyR6f6WaA/A
		MLUH1guMD8BzrpJ+kK8PwBDQiqAl0w/AYeVi38v2D8DJiOTrQQ0QwCff2RQn
		HxDAj91/rRUxEMC4OevwDUMQwMtHyjQQVRDA7NGZqhxnEMAtBM+GM3kQwGbW
		1PpUixDAkZn1IoGdEMAI1EIhuK8QwEw4RAj6wRDAwKXa3kbUEMDROL+enuYQ
		wHTQ4DIB+RDAXfWedW4LEcA2X+Mu5h0RwFqIGxJoMBHAhxcVvPNCEcBU0sCw
		iFURwEj8WLQOaBHAORV+y4R6EcBtGNUmB40RwF023TuVnxHAI1jReS6yEcBY
		Gsk20sQRwNc8xa5/1xHAFOWyAzbqEcDKcQQ99PwRwBacb0e5DxLAkW+y9IMi
		EsBRsFn7UjUSwKuExKQlSBLABTRgBf1aEsBd32Dc120SwKZOuou0gBLAfEeS
		U5GTEsAXpwZSbKYSwPPh2oJDuRLA1dj9vhTMEsB4fti73d4SwPGvUgqc8RLA
		dtx5FU0EE8ADSLIg7hYTwJ/KWEV8KRPAQJC2b/Q7E8COciVbU04TwE7anLqV
		YBPAcd4iac1yE8BIsiUSCIUTwPtBY5ZFlxPAxKsK0IWpE8DJjsOSyLsTwOo+
		w6sNzhPAQxTu4VTgE8BCpwX2nfITwIpL46LoBBTABoa+nTQXFMBKjn2WgSkU
		wPO/YgTLOxTAPmRWofFNFMDl1NY1FGAUwKRFtMsychTAOVmhbk2EFMDl4Rws
		ZJYUwAw2IRN3qBTADnOUM4a6FMAP6nWdkcwUwMldxF+Z3hTAaD8ah53wFMDp
		Y/sbngIVwC4/wSCbFBXAXJ9Nj5QmFcD2OWNXijgVwGBUQVl8ShXAI49dZGpc
		FcBAs/gyVG4VwCN0umU5gBXAWrvOfxmSFcCSQCzh86MVwP6ifsHHtRXA0Ith
		KpTHFcCy70TxV9kVwDZO4LAR6xXAnwffNsH8FcDZTH9wZw4WwH+5OQcPIBbA
		K+hMKL0xFsDpLYl2ckMWwIqzPEYgVRbAUJXdbdRmFsAapB76kngWwDYVwnJc
		ihbA8+BRVDGcFsABckgPEq4WwCNJIgf/vxbAZPRXkfjRFsD2Ujn0/uMWwHvv
		q2US9hbA+xzFCTMIF8DqPT7xYBoXwBpvwxecLBfA5t0UYuQ+F8CXJf+bOVEX
		wAiwJHabYxfAhPqZgwl2F8Ax41E3g4gXwIHUYOEHmxfAw1L/q5atF8AYhD9o
		DcAXwHGiGx6G0hfAhHIZAgvlF8Dq0jmlmvcXwIHl7lEzChjAMDehCNMcGMBJ
		OTuPdy8YwIr2278fQhjAz3jap8pUGMBt3RwTd2cYwANyYqsjehjAsACo9s6M
		GMDacVlWd58YwIVAHwYbshjArAN5GrjEGMDGc6F8TNcYwIOroPPV6RjAuHEq
		EFL8GMB6Ag43vg4ZwGqpopoXIRnAWDgkN1szGcB+KmbOhUUZwN+SuuKTVxnA
		sCrqsIFpGcBUYlu1VXsZwM8USuYjjRnAGIGa5+yeGcAj0eS2sLAZwDGul1Fv
		whnA7/n2tCjUGcCJVhne3OUZwMHj5cmL9xnAwK8SdTUJGsA6piHc2RoawKJ1
		cvh4LBrABEPEyxI+GsCtYEsbrE8awEh1ZCBNYRrASoHkZfdyGsCMcZVVrIQa
		wDfYxEhtlhrATFdFhTuoGsC2JVo6GLoawIR1ln0EzBrAXsO0RwHeGsBHpHNx
		D/AawAKugrAvAhvAL5mJlGIUG8Cf8liEqCYbwIr4ULsBORvARloKR25LG8BG
		Dk4F7l0bwB4PaaKAcBvAbWTmlyWDG8Bcl7gr3JUbwMJA2W+jqBvAxNBiQnq7
		G8BUtiROX84bwDOT9+034RvAABz/WsfzG8AXJ8pacAYcwAuTp+YwGRzAKeuI
		ogYsHMCLN3Pf7j4cwL56PJ7mURzAT3pqkupkHMCsSDEl93ccwDgRbngIixzA
		O2IRaRqeHMA2FOqQKLEcwOzmyEcuxBzA2BipoybXHMDa+ZV3DOocwJOfA1Ha
		/BzAZP1c4YgPHcDJZz7SCSIdwFGsmYlWNB3A0fVKeWlGHcAEcRucPFgdwMtL
		U0/JaR3AEAbAQgp7HcBlOd02LIwdwMayieREnR3AygLwdVWuHcBJ3c8MX78d
		wE5ypsBi0B3Ad1/nnGHhHcAyMUufXPIdwIIBN7ZUAx7At/xEv0oUHsACRe+F
		PyUewH8iZMIzNh7Ab9uEGChHHsDEHRQXHVgewIdE2NIHaR7Azd/PD+B5HsDp
		4ZCMvooewFlEk3ijmx7A7K8p3o6sHsA6s7qigL0ewDGfL4d4zh7Ah4+HKHbf
		HsAS9YEAefAewERDTWaAAR/AKzooj4sSH8Dcft6OmSMfwP3KCVipNB/A3LL7
		u7lFH8DgvzBqyVYfwGBbKO/WZx/AsDHdseB4H8C1FJfz5IkfwPsqY/fhmh/A
		TmzpRdqrH8CVuRCC0LwfwBV51KHEzR/AcIs78a7eH8Cx2Zodke8fwA+Dmag2
		ACDAFEWz0aIIIMBtU+MLDhEgwLBqpE55GSDAuL/KhuUhIMC6nSyWUyogwDI2
		QVPEMiDAdaWoiDg7IMB5G5D0sEMgwPyP40cuTCDATd1AJbFUIMD5RJ4fOl0g
		wEjFerjJZSDAFD1IXmBuIMDqxMQh+HYgwNtXxz9xfyDAEKRCAO+HIMDGVemI
		fJAgwJmIDfUZmSDA0XwLHMehIMCsV8mHg6ogwJR4uWpOsyDALqJ9CCe8IMDH
		umPlDsUgwKaQdEcFziDAtVHhiQjXIMAKlNiAFuAgwMcVKGos6SDAsfnu3Uby
		IMDwagjAYfsgwG43BDN4BCHAWa6xjYQNIcAAdG9UgBYhwAyonD5lHyHALFxa
		+zMoIcCWDNZnAjEhwNkfx+nWOSHAobOqaLFCIcAZbiuukUshwO/beWV3VCHA
		MMHkGmJdIcBmeSArR2YhwEld2u0PbyHA7evS6eJ3IcD5rZAwv4AhwBERvp6j
		iSHAeKud3I6SIcCE37Bef5shwKWqfmZzpCHATo1iA2mtIcDi0VQTXrYhwKo9
		S0NQvyHAcQC0Dz3IIcC8AwjEIdEhwFUc6Xn72SHAGF86F8fiIcClentLgesh
		wGWh4oom9CHAkulXCLP8IcDyhaesIgUiwJqW/1lxDSLAciC+rK8VIsCanr9J
		6R0iwACeRzgeJiLASrCxf04uIsA4YXgnejYiwJkUMBqhPiLApzjOIr5GIsC6
		auJez04iwInbyinWViLATL1+4tNeIsDCvhjkyWYiwNwypZi5biLAVqRLTaR2
		IsDXV3Yni34iwLO/yzJvhiLAXnBiZ1GOIsBjTF+wMpYiwP8hBPITniLAcXpu
		DvalIsA6aKHo2a0iwH00zWXAtSLAtM9trqG9IsB8SfQEesUiwE4kSv5ZzSLA
		eUU+rELVIsDw1IsoNd0iwCF6soYy5SLADfTpwjvtIsB4ujIdQvUiwEF09CIw
		/SLAuwJ2gTUFI8Ch/mvoUQ0jwGSxy2OEFSPAQ6nAYcodI8DMADqHHyYjwCgZ
		lbl+LiPATMjiDeE2I8CgIyuLQD8jwGJl3XugRyPAx/TkvP5PI8AoctA+WFgj
		wLhBwKGpYCPAbriSKO9oI8Dm/5mpJHEjwOiren1FeSPAR3wYbUyBI8DeZ9eU
		NYkjwB/8m3AUkSPAWsVZJgGZI8BKkC7d6aAjwPdoHQvMqCPAaa0HuaewI8Ad
		/LPvfLgjwBhXz7dLwCPAnu3tGRTII8CXkYoe1s8jwEybDs6R1yPAD2/HMEff
		I8DkBu9O9uYjwC2cqjCf7iPAYUoL3kH2I8DNpg5f3v0jwLBQn7t0BSTAbHWV
		+wQNJMBZULcmjxQkwG6fuUQTHCTAsxRAXZEjJMC4vt13CSskwJBsFZx7MiTA
		Twta0ec5JMDrAA8fTkEkwDp/iIyuSCTABtULIQlQJMAVus/jXVckwF2Y/Nus
		XiTA
		</data>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string>Pasteboard</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string>N=6, η=0.1</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>40</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>38</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>39</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSColorSpace</key>
			<integer>1</integer>
			<key>NSRGB</key>
			<data>
			MSAwIDAA
			</data>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>21</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>42</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>43</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>45</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>46</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>48</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>49</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>51</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>52</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>12</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSMutableArray</string>
				<string>NSArray</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSMutableArray</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>53</integer>
			</dict>
			<key>NS.objects</key>
			<array/>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>53</integer>
			</dict>
			<key>NS.objects</key>
			<array/>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>57</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>59</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>58</integer>
				</dict>
			</array>
		</dict>
		<string>NSColor pasteboard type</string>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>63</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>61</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>62</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>58</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSColorSpace</key>
			<integer>3</integer>
			<key>NSWhite</key>
			<data>
			MQA=
			</data>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>63</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>65</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>66</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>58</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>69</integer>
			</dict>
			<key>NSName</key>
			<dict>
				<key>CF$UID</key>
				<integer>68</integer>
			</dict>
			<key>NSSize</key>
			<real>14</real>
			<key>NSfFlags</key>
			<integer>272</integer>
		</dict>
		<string>Helvetica</string>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSFont</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSFont</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>71</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>72</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>58</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>63</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>74</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>75</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>58</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string>separation distance [au]</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>78</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>79</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>58</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>69</integer>
			</dict>
			<key>NSName</key>
			<dict>
				<key>CF$UID</key>
				<integer>68</integer>
			</dict>
			<key>NSSize</key>
			<real>18</real>
			<key>NSfFlags</key>
			<integer>272</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>69</integer>
			</dict>
			<key>NSName</key>
			<dict>
				<key>CF$UID</key>
				<integer>68</integer>
			</dict>
			<key>NSSize</key>
			<real>14</real>
			<key>NSfFlags</key>
			<integer>272</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>86</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>87</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>58</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>91</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>89</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>90</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>58</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>16</integer>
			</dict>
			<key>NSColorSpace</key>
			<integer>3</integer>
			<key>NSWhite</key>
			<data>
			MC4zMzMzMzMzMzMzAA==
			</data>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>93</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>94</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>58</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>91</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>96</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>97</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>58</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>91</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>99</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>100</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>58</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>106</integer>
			</dict>
			<key>NS.keys</key>
			<array/>
			<key>NS.objects</key>
			<array/>
		</dict>
		<dict>
			<key>$classes</key>
			<array>
				<string>NSMutableDictionary</string>
				<string>NSDictionary</string>
				<string>NSObject</string>
			</array>
			<key>$classname</key>
			<string>NSMutableDictionary</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string>solvation energy [kcal/mol]</string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>109</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>110</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>58</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>69</integer>
			</dict>
			<key>NSName</key>
			<dict>
				<key>CF$UID</key>
				<integer>68</integer>
			</dict>
			<key>NSSize</key>
			<real>18</real>
			<key>NSfFlags</key>
			<integer>272</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>69</integer>
			</dict>
			<key>NSName</key>
			<dict>
				<key>CF$UID</key>
				<integer>68</integer>
			</dict>
			<key>NSSize</key>
			<real>14</real>
			<key>NSfFlags</key>
			<integer>272</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>117</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>118</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>58</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>91</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>120</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>121</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>58</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>123</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>124</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>58</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>91</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>126</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>127</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>58</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>91</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>129</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>130</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>58</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>106</integer>
			</dict>
			<key>NS.keys</key>
			<array/>
			<key>NS.objects</key>
			<array/>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>138</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>139</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>58</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>69</integer>
			</dict>
			<key>NSName</key>
			<dict>
				<key>CF$UID</key>
				<integer>68</integer>
			</dict>
			<key>NSSize</key>
			<real>18</real>
			<key>NSfFlags</key>
			<integer>272</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>69</integer>
			</dict>
			<key>NSName</key>
			<dict>
				<key>CF$UID</key>
				<integer>68</integer>
			</dict>
			<key>NSSize</key>
			<real>14</real>
			<key>NSfFlags</key>
			<integer>272</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>146</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>147</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>58</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>91</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>149</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>150</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>58</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>152</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>153</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>58</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>91</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>155</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>156</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>58</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>91</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>158</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>159</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>58</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>106</integer>
			</dict>
			<key>NS.keys</key>
			<array/>
			<key>NS.objects</key>
			<array/>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>167</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>168</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>58</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>69</integer>
			</dict>
			<key>NSName</key>
			<dict>
				<key>CF$UID</key>
				<integer>68</integer>
			</dict>
			<key>NSSize</key>
			<real>18</real>
			<key>NSfFlags</key>
			<integer>272</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>69</integer>
			</dict>
			<key>NSName</key>
			<dict>
				<key>CF$UID</key>
				<integer>68</integer>
			</dict>
			<key>NSSize</key>
			<real>14</real>
			<key>NSfFlags</key>
			<integer>272</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>175</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>176</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>58</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>91</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>178</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>179</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>58</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>15</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>181</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>182</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>58</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>91</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>184</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>185</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>58</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>17</integer>
			</dict>
			<key>NSAllowsLogicalLayoutDirection</key>
			<false/>
			<key>NSColor</key>
			<dict>
				<key>CF$UID</key>
				<integer>91</integer>
			</dict>
			<key>NSDragTypes</key>
			<dict>
				<key>CF$UID</key>
				<integer>187</integer>
			</dict>
			<key>NSEnabled</key>
			<true/>
			<key>NSFrameSize</key>
			<dict>
				<key>CF$UID</key>
				<integer>188</integer>
			</dict>
			<key>NSIsBordered</key>
			<true/>
			<key>NSNextResponder</key>
			<dict>
				<key>CF$UID</key>
				<integer>0</integer>
			</dict>
			<key>NSvFlags</key>
			<integer>256</integer>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>13</integer>
			</dict>
			<key>NS.objects</key>
			<array>
				<dict>
					<key>CF$UID</key>
					<integer>58</integer>
				</dict>
			</array>
		</dict>
		<string>{0, 0}</string>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>7</integer>
			</dict>
			<key>NS.string</key>
			<string></string>
		</dict>
		<dict>
			<key>$class</key>
			<dict>
				<key>CF$UID</key>
				<integer>106</integer>
			</dict>
			<key>NS.keys</key>
			<array/>
			<key>NS.objects</key>
			<array/>
		</dict>
	</array>
	<key>$top</key>
	<dict>
		<key>alabel0</key>
		<dict>
			<key>CF$UID</key>
			<integer>105</integer>
		</dict>
		<key>alabel1</key>
		<dict>
			<key>CF$UID</key>
			<integer>135</integer>
		</dict>
		<key>alabel2</key>
		<dict>
			<key>CF$UID</key>
			<integer>164</integer>
		</dict>
		<key>alabel3</key>
		<dict>
			<key>CF$UID</key>
			<integer>193</integer>
		</dict>
		<key>align0</key>
		<integer>2</integer>
		<key>align1</key>
		<integer>4</integer>
		<key>align2</key>
		<integer>6</integer>
		<key>align3</key>
		<integer>8</integer>
		<key>alldraw</key>
		<false/>
		<key>angle0</key>
		<real>0.0</real>
		<key>angle1</key>
		<real>0.0</real>
		<key>angle2</key>
		<real>0.0</real>
		<key>angle3</key>
		<real>0.0</real>
		<key>arrowsize</key>
		<real>10</real>
		<key>arrowtype</key>
		<integer>0</integer>
		<key>axis0</key>
		<true/>
		<key>axis1</key>
		<true/>
		<key>axis2</key>
		<false/>
		<key>axis3</key>
		<false/>
		<key>axismode0</key>
		<integer>0</integer>
		<key>axismode1</key>
		<integer>0</integer>
		<key>axismode2</key>
		<integer>0</integer>
		<key>axismode3</key>
		<integer>0</integer>
		<key>axistext0</key>
		<dict>
			<key>CF$UID</key>
			<integer>76</integer>
		</dict>
		<key>axistext1</key>
		<dict>
			<key>CF$UID</key>
			<integer>107</integer>
		</dict>
		<key>axistext2</key>
		<dict>
			<key>CF$UID</key>
			<integer>136</integer>
		</dict>
		<key>axistext3</key>
		<dict>
			<key>CF$UID</key>
			<integer>165</integer>
		</dict>
		<key>axistextcolor0</key>
		<dict>
			<key>CF$UID</key>
			<integer>77</integer>
		</dict>
		<key>axistextcolor1</key>
		<dict>
			<key>CF$UID</key>
			<integer>108</integer>
		</dict>
		<key>axistextcolor2</key>
		<dict>
			<key>CF$UID</key>
			<integer>137</integer>
		</dict>
		<key>axistextcolor3</key>
		<dict>
			<key>CF$UID</key>
			<integer>166</integer>
		</dict>
		<key>axistimeformat0</key>
		<dict>
			<key>CF$UID</key>
			<integer>80</integer>
		</dict>
		<key>axistimeformat1</key>
		<dict>
			<key>CF$UID</key>
			<integer>111</integer>
		</dict>
		<key>axistimeformat2</key>
		<dict>
			<key>CF$UID</key>
			<integer>140</integer>
		</dict>
		<key>axistimeformat3</key>
		<dict>
			<key>CF$UID</key>
			<integer>169</integer>
		</dict>
		<key>backgroundcolor</key>
		<dict>
			<key>CF$UID</key>
			<integer>60</integer>
		</dict>
		<key>buffer</key>
		<dict>
			<key>CF$UID</key>
			<integer>2</integer>
		</dict>
		<key>crossarrows</key>
		<integer>0</integer>
		<key>dp0</key>
		<integer>2</integer>
		<key>dp1</key>
		<integer>2</integer>
		<key>dp2</key>
		<integer>2</integer>
		<key>dp3</key>
		<integer>2</integer>
		<key>dpauto0</key>
		<true/>
		<key>dpauto1</key>
		<true/>
		<key>dpauto2</key>
		<true/>
		<key>dpauto3</key>
		<true/>
		<key>drawbackground</key>
		<true/>
		<key>drawframe</key>
		<true/>
		<key>drawmargin</key>
		<true/>
		<key>expoff0</key>
		<integer>5</integer>
		<key>expoff1</key>
		<integer>5</integer>
		<key>expoff2</key>
		<integer>5</integer>
		<key>expoff3</key>
		<integer>5</integer>
		<key>fliptext0</key>
		<false/>
		<key>fliptext1</key>
		<false/>
		<key>fliptext2</key>
		<false/>
		<key>fliptext3</key>
		<false/>
		<key>forceframe</key>
		<false/>
		<key>forcerenderhigh</key>
		<false/>
		<key>framearrows</key>
		<false/>
		<key>framecolor</key>
		<dict>
			<key>CF$UID</key>
			<integer>56</integer>
		</dict>
		<key>framestyle</key>
		<integer>0</integer>
		<key>framewidth</key>
		<real>2</real>
		<key>graphic</key>
		<dict>
			<key>CF$UID</key>
			<integer>55</integer>
		</dict>
		<key>grid0</key>
		<false/>
		<key>grid1</key>
		<false/>
		<key>grid2</key>
		<false/>
		<key>grid3</key>
		<false/>
		<key>gridcolor0</key>
		<dict>
			<key>CF$UID</key>
			<integer>88</integer>
		</dict>
		<key>gridcolor1</key>
		<dict>
			<key>CF$UID</key>
			<integer>119</integer>
		</dict>
		<key>gridcolor2</key>
		<dict>
			<key>CF$UID</key>
			<integer>148</integer>
		</dict>
		<key>gridcolor3</key>
		<dict>
			<key>CF$UID</key>
			<integer>177</integer>
		</dict>
		<key>gridfront0</key>
		<true/>
		<key>gridfront1</key>
		<true/>
		<key>gridfront2</key>
		<true/>
		<key>gridfront3</key>
		<true/>
		<key>gridpattern0</key>
		<integer>0</integer>
		<key>gridpattern1</key>
		<integer>0</integer>
		<key>gridpattern2</key>
		<integer>0</integer>
		<key>gridpattern3</key>
		<integer>0</integer>
		<key>gridwidth0</key>
		<real>0.5</real>
		<key>gridwidth1</key>
		<real>0.5</real>
		<key>gridwidth2</key>
		<real>0.5</real>
		<key>gridwidth3</key>
		<real>0.5</real>
		<key>legendalign</key>
		<integer>0</integer>
		<key>legendbg</key>
		<false/>
		<key>legendbgcolor</key>
		<dict>
			<key>CF$UID</key>
			<integer>73</integer>
		</dict>
		<key>legendcolor</key>
		<dict>
			<key>CF$UID</key>
			<integer>70</integer>
		</dict>
		<key>legendfont</key>
		<dict>
			<key>CF$UID</key>
			<integer>67</integer>
		</dict>
		<key>legendhorizontal</key>
		<false/>
		<key>legendspace</key>
		<integer>20</integer>
		<key>legendwidth</key>
		<integer>40</integer>
		<key>legendx</key>
		<integer>350</integer>
		<key>legendy</key>
		<integer>370</integer>
		<key>marginbottom</key>
		<real>60</real>
		<key>margincolor</key>
		<dict>
			<key>CF$UID</key>
			<integer>64</integer>
		</dict>
		<key>marginleft</key>
		<real>80</real>
		<key>marginright</key>
		<real>10</real>
		<key>margintop</key>
		<real>10</real>
		<key>mgrid0</key>
		<false/>
		<key>mgrid1</key>
		<false/>
		<key>mgrid2</key>
		<false/>
		<key>mgrid3</key>
		<false/>
		<key>mgridcolor0</key>
		<dict>
			<key>CF$UID</key>
			<integer>95</integer>
		</dict>
		<key>mgridcolor1</key>
		<dict>
			<key>CF$UID</key>
			<integer>125</integer>
		</dict>
		<key>mgridcolor2</key>
		<dict>
			<key>CF$UID</key>
			<integer>154</integer>
		</dict>
		<key>mgridcolor3</key>
		<dict>
			<key>CF$UID</key>
			<integer>183</integer>
		</dict>
		<key>mgridfront0</key>
		<true/>
		<key>mgridfront1</key>
		<true/>
		<key>mgridfront2</key>
		<true/>
		<key>mgridfront3</key>
		<true/>
		<key>mgridpattern0</key>
		<integer>0</integer>
		<key>mgridpattern1</key>
		<integer>0</integer>
		<key>mgridpattern2</key>
		<integer>0</integer>
		<key>mgridpattern3</key>
		<integer>0</integer>
		<key>mgridwidth0</key>
		<real>0.5</real>
		<key>mgridwidth1</key>
		<real>0.5</real>
		<key>mgridwidth2</key>
		<real>0.5</real>
		<key>mgridwidth3</key>
		<real>0.5</real>
		<key>mtickcolor0</key>
		<dict>
			<key>CF$UID</key>
			<integer>92</integer>
		</dict>
		<key>mtickcolor1</key>
		<dict>
			<key>CF$UID</key>
			<integer>122</integer>
		</dict>
		<key>mtickcolor2</key>
		<dict>
			<key>CF$UID</key>
			<integer>151</integer>
		</dict>
		<key>mtickcolor3</key>
		<dict>
			<key>CF$UID</key>
			<integer>180</integer>
		</dict>
		<key>mticklength0</key>
		<real>5</real>
		<key>mticklength1</key>
		<real>5</real>
		<key>mticklength2</key>
		<real>5</real>
		<key>mticklength3</key>
		<real>5</real>
		<key>mticks0</key>
		<true/>
		<key>mticks1</key>
		<true/>
		<key>mticks2</key>
		<true/>
		<key>mticks3</key>
		<true/>
		<key>mticksboth0</key>
		<false/>
		<key>mticksboth1</key>
		<false/>
		<key>mticksboth2</key>
		<false/>
		<key>mticksboth3</key>
		<false/>
		<key>mtickwidth0</key>
		<real>1</real>
		<key>mtickwidth1</key>
		<real>1</real>
		<key>mtickwidth2</key>
		<real>1</real>
		<key>mtickwidth3</key>
		<real>1</real>
		<key>numbers0</key>
		<true/>
		<key>numbers1</key>
		<true/>
		<key>numbers2</key>
		<true/>
		<key>numbers3</key>
		<true/>
		<key>numfont0</key>
		<dict>
			<key>CF$UID</key>
			<integer>84</integer>
		</dict>
		<key>numfont1</key>
		<dict>
			<key>CF$UID</key>
			<integer>115</integer>
		</dict>
		<key>numfont2</key>
		<dict>
			<key>CF$UID</key>
			<integer>144</integer>
		</dict>
		<key>numfont3</key>
		<dict>
			<key>CF$UID</key>
			<integer>173</integer>
		</dict>
		<key>numoff0</key>
		<integer>5</integer>
		<key>numoff1</key>
		<integer>5</integer>
		<key>numoff2</key>
		<integer>5</integer>
		<key>numoff3</key>
		<integer>5</integer>
		<key>plotlegend</key>
		<true/>
		<key>plotversion</key>
		<dict>
			<key>CF$UID</key>
			<integer>1</integer>
		</dict>
		<key>reverse0</key>
		<false/>
		<key>reverse1</key>
		<false/>
		<key>reverse2</key>
		<false/>
		<key>reverse3</key>
		<false/>
		<key>scaleexpr0</key>
		<dict>
			<key>CF$UID</key>
			<integer>81</integer>
		</dict>
		<key>scaleexpr1</key>
		<dict>
			<key>CF$UID</key>
			<integer>112</integer>
		</dict>
		<key>scaleexpr2</key>
		<dict>
			<key>CF$UID</key>
			<integer>141</integer>
		</dict>
		<key>scaleexpr3</key>
		<dict>
			<key>CF$UID</key>
			<integer>170</integer>
		</dict>
		<key>scalend0</key>
		<dict>
			<key>CF$UID</key>
			<integer>102</integer>
		</dict>
		<key>scalend1</key>
		<dict>
			<key>CF$UID</key>
			<integer>132</integer>
		</dict>
		<key>scalend2</key>
		<dict>
			<key>CF$UID</key>
			<integer>161</integer>
		</dict>
		<key>scalend3</key>
		<dict>
			<key>CF$UID</key>
			<integer>190</integer>
		</dict>
		<key>scalminticks0</key>
		<dict>
			<key>CF$UID</key>
			<integer>104</integer>
		</dict>
		<key>scalminticks1</key>
		<dict>
			<key>CF$UID</key>
			<integer>134</integer>
		</dict>
		<key>scalminticks2</key>
		<dict>
			<key>CF$UID</key>
			<integer>163</integer>
		</dict>
		<key>scalminticks3</key>
		<dict>
			<key>CF$UID</key>
			<integer>192</integer>
		</dict>
		<key>scalspace0</key>
		<dict>
			<key>CF$UID</key>
			<integer>103</integer>
		</dict>
		<key>scalspace1</key>
		<dict>
			<key>CF$UID</key>
			<integer>133</integer>
		</dict>
		<key>scalspace2</key>
		<dict>
			<key>CF$UID</key>
			<integer>162</integer>
		</dict>
		<key>scalspace3</key>
		<dict>
			<key>CF$UID</key>
			<integer>191</integer>
		</dict>
		<key>scalstart0</key>
		<dict>
			<key>CF$UID</key>
			<integer>101</integer>
		</dict>
		<key>scalstart1</key>
		<dict>
			<key>CF$UID</key>
			<integer>131</integer>
		</dict>
		<key>scalstart2</key>
		<dict>
			<key>CF$UID</key>
			<integer>160</integer>
		</dict>
		<key>scalstart3</key>
		<dict>
			<key>CF$UID</key>
			<integer>189</integer>
		</dict>
		<key>smalllog0</key>
		<false/>
		<key>smalllog1</key>
		<false/>
		<key>smalllog2</key>
		<false/>
		<key>smalllog3</key>
		<false/>
		<key>subviews</key>
		<integer>0</integer>
		<key>text</key>
		<dict>
			<key>CF$UID</key>
			<integer>54</integer>
		</dict>
		<key>text0</key>
		<true/>
		<key>text1</key>
		<true/>
		<key>text2</key>
		<true/>
		<key>text3</key>
		<true/>
		<key>textfont0</key>
		<dict>
			<key>CF$UID</key>
			<integer>83</integer>
		</dict>
		<key>textfont1</key>
		<dict>
			<key>CF$UID</key>
			<integer>114</integer>
		</dict>
		<key>textfont2</key>
		<dict>
			<key>CF$UID</key>
			<integer>143</integer>
		</dict>
		<key>textfont3</key>
		<dict>
			<key>CF$UID</key>
			<integer>172</integer>
		</dict>
		<key>textoff0</key>
		<integer>5</integer>
		<key>textoff1</key>
		<integer>5</integer>
		<key>textoff2</key>
		<integer>5</integer>
		<key>textoff3</key>
		<integer>5</integer>
		<key>textoffsetfromframe0</key>
		<false/>
		<key>textoffsetfromframe1</key>
		<false/>
		<key>textoffsetfromframe2</key>
		<false/>
		<key>textoffsetfromframe3</key>
		<false/>
		<key>tickcolor0</key>
		<dict>
			<key>CF$UID</key>
			<integer>85</integer>
		</dict>
		<key>tickcolor1</key>
		<dict>
			<key>CF$UID</key>
			<integer>116</integer>
		</dict>
		<key>tickcolor2</key>
		<dict>
			<key>CF$UID</key>
			<integer>145</integer>
		</dict>
		<key>tickcolor3</key>
		<dict>
			<key>CF$UID</key>
			<integer>174</integer>
		</dict>
		<key>ticklength0</key>
		<real>10</real>
		<key>ticklength1</key>
		<real>10</real>
		<key>ticklength2</key>
		<real>10</real>
		<key>ticklength3</key>
		<real>10</real>
		<key>ticks0</key>
		<true/>
		<key>ticks1</key>
		<true/>
		<key>ticks2</key>
		<true/>
		<key>ticks3</key>
		<true/>
		<key>ticksboth0</key>
		<false/>
		<key>ticksboth1</key>
		<false/>
		<key>ticksboth2</key>
		<false/>
		<key>ticksboth3</key>
		<false/>
		<key>tickstyle0</key>
		<integer>0</integer>
		<key>tickstyle1</key>
		<integer>0</integer>
		<key>tickstyle2</key>
		<integer>0</integer>
		<key>tickstyle3</key>
		<integer>0</integer>
		<key>tickwidth0</key>
		<real>2</real>
		<key>tickwidth1</key>
		<real>2</real>
		<key>tickwidth2</key>
		<real>2</real>
		<key>tickwidth3</key>
		<real>2</real>
		<key>trigger0</key>
		<dict>
			<key>CF$UID</key>
			<integer>82</integer>
		</dict>
		<key>trigger1</key>
		<dict>
			<key>CF$UID</key>
			<integer>113</integer>
		</dict>
		<key>trigger2</key>
		<dict>
			<key>CF$UID</key>
			<integer>142</integer>
		</dict>
		<key>trigger3</key>
		<dict>
			<key>CF$UID</key>
			<integer>171</integer>
		</dict>
		<key>verno</key>
		<integer>31</integer>
		<key>winh</key>
		<integer>400</integer>
		<key>winw</key>
		<integer>500</integer>
		<key>winx</key>
		<integer>47</integer>
		<key>winy</key>
		<integer>455</integer>
		<key>xmax1</key>
		<real>7.0085224390243903</real>
		<key>xmax2</key>
		<real>1</real>
		<key>xmin1</key>
		<real>1.5207175609756098</real>
		<key>xmin2</key>
		<real>0.0</real>
		<key>ymax1</key>
		<real>-1.1353317571903254</real>
		<key>ymax2</key>
		<real>1</real>
		<key>ymin1</key>
		<real>-10.733372004688084</real>
		<key>ymin2</key>
		<real>0.0</real>
		<key>zerocolor0</key>
		<dict>
			<key>CF$UID</key>
			<integer>98</integer>
		</dict>
		<key>zerocolor1</key>
		<dict>
			<key>CF$UID</key>
			<integer>128</integer>
		</dict>
		<key>zerocolor2</key>
		<dict>
			<key>CF$UID</key>
			<integer>157</integer>
		</dict>
		<key>zerocolor3</key>
		<dict>
			<key>CF$UID</key>
			<integer>186</integer>
		</dict>
		<key>zeroline0</key>
		<false/>
		<key>zeroline1</key>
		<false/>
		<key>zeroline2</key>
		<false/>
		<key>zeroline3</key>
		<false/>
	</dict>
	<key>$version</key>
	<integer>100000</integer>
</dict>
</plist>
